config/routes.rb
Rphenomenal::Application.routes.draw do
  root :to=> "Pages#home"
  match "/project", :to => "Pages#project"
  match "/api", :to => "Pages#api"
  match "/introspection", :to => "Pages#introspection"
  match "/presentations/thesis", :to => "Presentations#thesis"
  resource :newsletters
  resource :application_states
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title="Home"
    @applicationState=ApplicationState.load(cookies)
  end

  def project
    @title="Project Description"
  end

  def api
    @title="Application Programming Interface"
  end

  def introspection
    @title="Introspection"
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  layout "presentation"

  def thesis
    @title="Thesis presentation"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Phenomenal Gem"
    if @title
      "#{base_title} | #{@title}"
    else
      base_title
    end
  end
  
  def to_hex_string(color)
    color = 255 if color>255
    color = 0 if color<0
    ret = color.to_s(16)
    ret = "0#{color}" if ret.size==1
    ret
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  
  def phenomenal_color(r, g, b)
    "\##{to_hex_string(r)}#{to_hex_string(g)}#{to_hex_string(b)}"
  end
  
  def display_phenomenal_use_diagram
    image_tag("project/phenomenal_use_diagram.png")
  end
  
  def phenomenal_contexts_images
    []
  end
end

app/helpers/presentation_helper.rb
module PresentationHelper
  def pygments(file,lexer=:ruby)
    raw Pygments.highlight(File.read("#{Rails.root}/#{file}"), :lexer=>lexer)
  end

#  def pygments_inline(content,lexer=:ruby)
#   raw Pygments.highlight(content), :lexer=>lexer).gsub(/<\/*pre>/,"").gsub(/<div class="highlight">/,"<span class=\"highlight\">").gsub(/<\/div>/,"")
#  end
end

app/views/announces/_index.html.haml
=render "shared/deactivated_module"

app/views/contexts/_index.html.haml
=render "shared/deactivated_module"

app/views/layouts/_footer.html.haml
.row-fluid
  .span12#footer{:style=>"background-color:#{phenomenal_color(127,127,127)}"}
    .container
      =mail_to "team@phenomenal-gem.com" ,"Thibault Poncelet"
      \| 
      =mail_to "team@phenomenal-gem.com" , "Loic Vigneron"
      \| 
      =link_to "RELEASeD laboratory","http://released.info.ucl.ac.be/Research/ContextOrientedProgramming"

app/views/layouts/_header.html.haml
.row-fluid#header_top{:style=>"background-color:#{phenomenal_color(127,127,127)}"}
  .container
    .span6#logo_top
      =link_to image_tag("phen_logo_top.png"), :root
    .span6
      %ul#menu.nav.nav-pills
        %li= link_to "Home", root_path, {:class=>"active big_link"}
        //        %li.dropdown
        //          =link_to "Project",project_path,{:class=>"dropdown-toggle big_link", "data-toggle"=>"dropdown"}
        %li.dropdown
          =link_to "Documentation","#",{:class=>"dropdown-toggle big_link", "data-toggle"=>"dropdown"}
          %ul.dropdown-menu
            %li=link_to "API", api_path
        %li=link_to "Introspection",introspection_path, {:class=>"active big_link"}
        %li=link_to "Presentation", presentations_thesis_path,{:class=>"active big_link"}

.row-fluid#header_bottom
  .container
    .span2#logo_bottom
      =link_to image_tag("phen_logo_bottom.png"), :root
    .span10#content
      =yield :header_content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(http-equiv="content-Type" content="text/html; charset=UTF-8")
    %title= title
    = favicon_link_tag('/favicon.png')
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield :head
    -if Rails.env.production? 
      <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28736734-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
      </script>
  %body
    = render "layouts/header"
    .container
      #body
        - [:notice, :error, :message, :success].each do |key|
          - unless flash[key].blank?
            %div{ :class => "flash #{key}" }= flash[key] 
        = yield
        .clear
    = render 'layouts/footer'
    = debug(params) if Rails.env.development? 
      

app/views/layouts/presentation.html.haml
!!!
%html
  // Original Slides implemntation from http://slides.html5rocks.com/#title-slide
  %head
    %title= title
    = favicon_link_tag('/favicon.png')
    = csrf_meta_tag
    %meta(http-equiv="content-Type" content="text/html; charset=UTF-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1")
    %link{:href=>"http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Sans+Mono", :rel=>"stylesheet", :type=>"text/css"}
    = stylesheet_link_tag "presentation"
    = yield :head

    -if Rails.env.production?
      <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28736734-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
      </script>
  %body
    %nav{:id=>"helpers"}

      %button{:title=>"Previous slide", :id=>"nav-prev", :class=>"nav-prev"}  ⇽
      %button{:title=>"Jump to a random slide", :id=>"slide-no"} 5
      %button{:title=>"Next slide", :id=>"nav-next", :class=>"nav-next"} ⇾


      %menu
        %button{:type=>"checkbox", "data-command"=>"toc", :title=>"Table of Contents", :class=>"toc"} TOC
        %button{:type=>"checkbox", "data-command"=>"help", :title=>"View Help"} ?
        %button=link_to "⌂", :root,:title=>"Phenomenal Gem Home"
    .presentation
      #presentation-counter{:style=>"display: none;"} Loading...
      .slides
        = yield
    #speaker-note.invisible{:style=>"display: none;"}
    %aside{:id=>"help", :class=>"sidebar invisible",:style=>"display: hidden;"}
      %table
        %caption Help
        %tbody
          %tr
            %th Move Around
            %td &larr;&nbsp;&rarr;
          %tr
            %th Source File
            %td s
          //%tr
          //  %th Change Theme
          //  %td t
          //%tr
          //  %th Syntax Highlight
          //  %td h
          %tr
            %th Speaker Notes
            %td n
          %tr
            %th Toggle 3D
            %td 3
          %tr
            %th Help
            %td 0
    = javascript_include_tag "presentation"

app/views/newsletters/_form.html.haml
=render "shared/deactivated_module"

app/views/pages/api.html.haml
.documentation
  %h1=@title
  %h2 Phenomenal Gem
  %h3 Context Management
  
  %h4 
    phen_context(context[,contexts...],&block) → context
    %br
    context(context[,contexts...],&block) → context
  %p
    Defines a new (combined) context.
    
  %h4 
    phen_feature(context[,contexts...],&block) → feature
    %br
    feature(context[,contexts...],&block) → feature
  %p
    Defines a new (combined) feature.
    
  %h4 
    adaptations_for(klass) → klass
  %p
    Must be called in the body of a context or feature, defines the class for which the
    following adaptation defined with 
    %tt adapt 
    and 
    %tt adapt 
    class belong.
    
  %h4
    adapt(method,&block) → nil
  %p
    Must be called in the body of a context or feature, defines an adaptation for the instance method in the class specified by the previous call to 
    %tt adaptations_for.
    
  %h4
    adapt_class(method,&block) → nil
  %p
    Must be called in the body of a context or feature, defines an adaptation for the class method in the class specified by the previous call to 
    %tt adaptations_for.
    
  %h4
    phen_forget_context(context) → nil
  %p
    Removes a context from the system.
    
  %h4
    phen_activate_context(context[,contexts...]) → context or feature 
    %br
    activate_context(context[,contexts...]) → context or feature
  %p
    Activates the context or feature.
    
  %h4
    phen_deactivate_context(context[,contexts...]) → context or feature 
    %br
    deactivate_context(context[,contexts...]) → context or feature
  %p
    Deactivates the context or feature.
    
  %h4
    phen_context_active?(context) → true or false
  %p
    Returns true when the context is currently active.
    
  %h4
    phen_context_information(context) → hash
  %p
    Returns details about the context:
    %ul
      %li name: the name of the context.
      %li adaptations: an array of the context adaptations.
      %li active: true if the context is active, false otherwise.
      %li age: the activation age of the context.
      %li activation count: the number of activations of the context since the last actual deactivation.
      %li type: either Phenomenal::Context or Phenomenal::Feature.
  %h4
    phen_default_feature → feature
  %p
    Returns the default feature of the system. This feature represents the base application.
  %h4
    phen_defined_contexts → array  
  %p
    Returns an array containing all the contexts and features defined in the system.
    
  %h3 Adaptations Management
  %h4
    phen_add_adaptation(context,klass, method_name, &body) → adaptation
  %p
    Creates and returns a new adaptation for the instance method in klass into context.
  %h4
    phen_add_class_adaptation(context,klass, method_name, &body) → adaptation
  %p
    Creates and returns a new adaptation for the class method in klass into context.
    
  %h4
    phen_remove_adaptation(context,klass, method name) → adaptation
  %p  
    Deletes and returns the adaptation for the instance method in klass from context.
  %h4
    phen_remove_class_adaptation(context,klass, method name) → adaptation 
  %p
    Deletes and returns the adaptation for the class method in klass from context.
  %h4
    phen_proceed([args...],&block) → object
    %br
    proceed([args...],&block) → object
  %p  
    Must be called into the body of an adaptation, returns the evaluation of the next method with less precedence according to the conflict policy. The arguments are passed to this next method.
  %h4
    phen_change_conflict_policy(&block) → nil
  %p
    Sets a new conflict policy for the system. The block takes two contexts in argument and has to return -1 if first context has precedence on the second, 1 in the opposite case and raise a Phenomenal::Error if the conflict is not resolvable.
    
  %h3 Relationships Management
  %h4  
    phen_requirements_for(source,:on=>[targets]) → nil
    %br
    requirements_for(source,:on=>[targets]) → nil
  %p
    Define a requirement relationship for source on targets. When called in the body of a feature, this relationship is stored into it. Otherwise, stored in the default feature.
  %h4  
    phen_implications_for(source,:on=>[targets]) → nil
    %br
    implications_for(source,:on=>[targets]) → nil
  %p
    Define a implication relationship for source on targets. When called in the body of a feature, this relationship is stored into it. Otherwise, stored in the default feature.
  %h4  
    phen_suggestions_for(source,:on=>[targets]) → nil 
    %br
    suggestions_for(source,:on=>[targets]) → nil
  %p
    Define a suggestion relationship for source on targets. When called in the body of a feature, this relationship is stored into it. Otherwise, stored in the default feature.
  
  %h4  
    requires(context,[contexts,..]) → nil
  %p
    Must be called in the body of a context, defines a requirement relationship in its closest parent feature on the contexts in parameters.

  %h4
    implies(context,[contexts,..]) → nil
  %p  
    Must be called in the body of a context, defines a implication relationship in its closest parent feature on the contexts in parameters.

  %h4  
    suggests(context,[contexts,..]) → nil
  %p
    Must be called in the body of a context, defines a suggestion relationship in its closest parent feature on the contexts in parameters.

  %h3 Debugging

  %h4
    phen_textual_view → string
  %p  
    Returns a textual representation of the current state of the system.
  %h4  
    phen_graphical_view(file) → nil
  %p  
    Generates a graphical representation of the current state of the system.
    
  %h2 Phenomenal Rails Gem
  %h4
    is_persistent → context
  %p  
    Must be called in a feature or context, states that the contexts is always active in the system.
  %h4  
    activation_condition(&block) → nil
  %p  
    Must be called in a feature, specifies the logic to activate contexts before each HyperText Transfer Protocol (HTTP) request. The block defining logic has access to the Rack environment through the parameter env. This activation condition is only applied when the surrounding feature is active.    

  

app/views/pages/home.html.haml
-content_for :header_content do
  Phenomenal Gem is a context-oriented framework implemented in Ruby that allows context-oriented programming in Ruby and Ruby on Rails applications.
    
.row-fluid
  .span4
    %h2 Pimp Your App
    #customizer.well
      =render "shared/customize_form"
  .span8
    %h2 Keep in Touch
    #news.well   
      =render "announces/index"
    %h2 Contexts Overview
    #analyser.well   
      =render "contexts/index"
.row-fluid
  .row-fluid
    .span12
      %h2 We Are Everywhere
    .row-fluid
      .span4
        #rubygems.social.well
          =link_to "http://rubygems.org/profiles/phenomenal" do
            .social_logo
              =image_tag "socials/RubyGems-48.png"
            .social_content
              %strong gem install phenomenal
              %br
              %strong gem install phenomenal_rails
          .clear
      .span4
        #github.social.well
          =link_to "https://github.com/phenomenal" do
            .social_logo
              =image_tag "socials/Github-48.png"
            .social_content
              %strong Phenomenal Gem
          .clear
      .span4
        #twitter.social.well
          =link_to "The_Phenomenal_Gem_Poncelet_Vigneron_2012.pdf" do
            .social_logo
              =image_tag "socials/PDF-File-48.png"
            .social_content
              %strong The Phenomenal Gem Thesis
          .clear
.row-fluid
  .span12      
    %h2 Damn What Is Phenomenal Gem?
    .well
      %p
      The Phenomenal Gem is a 
      %acronym{:title=>"Context-Oriented Programming"} COP
      framework for the dynamic programming language Ruby. With this framework, programmers can handle contexts as first-class entities allowing them to adapt the behaviour of their applications dynamically in a clean and structured manner. In addition to this 
      %acronym{:title=>"Context-Oriented Programming"} COP 
      framework, the thesis also introduces the notion of 
      %acronym{:title=>"Context as a Feature"} CaaF 
      that tries to merge the best of 
      %acronym{:title=>"Context-Oriented Programming"} COP
      and 
      %acronym{:title=>"Feature-Oriented Programming"} FOP 
      into a single new paradigm. From the point of view of usability in today’s web application, this thesis builds the notion of 
      %acronym{:title=>"Feature as a Service"} FaaS 
      on top of 
      %acronym{:title=>"Context as a Feature"} CaaF
      , and integrates it in the Ruby on Rails web framework. The implementation and semantics of these concepts are presented in detail and validated by a real-world case study of a 
      %acronym{:title=>"Software as a Service"} SaaS
      %acronym{:title=>"Enterprise Resource Planning"} ERP 
      application, developed by an industrial collaborator.

app/views/pages/introspection.html.haml
.row-fluid
  .span12
    %h2 System's Features and Contexts
    %table{:class=>"table table-striped"}
      %thead
        %th Name
        %th Type
        %th State
        %th Activation count
        %th Adaptations
      %tbody
        -phen_defined_contexts.each do |c|
          =render "shared/context", :context=>c

app/views/pages/project.html.haml
=render "shared/keep_calm"

app/views/presentations/thesis.html.haml
.slide#landing-slide
  %section.middle
    %hgroup
    %h1 The Phenomenal Gem
    %h2 Putting Feature as a Service on Rails
    %span{:id=>"left-init-key"}
    =image_tag("pheno_logo.png")
    %h3 Thibault Poncelet & Loïc Vigneron
    %h4
      Computing Science Engineering Department, UCL
    %h4
      June 2012

.slide#table-of-contents
  %header
    %h1 Contents
  %section
    %ol#toc-list

// ======== Introduction ========
.slide.transitionSlide#introduction
  %section.middle
    %h2 Introduction
    %p
.slide
  %header
    %h1 Introduction
  %section.middle
    %p
      %strong From
      isolated desktop
      %strong to
      multi-user, customizable applications
    .big-arrow
      ⇩
    %p
      People expect applications to adapt to their needs
    %p
      =link_to "www.phenomenal-gem.com", :root

// ======== Motivation ========
.slide.transitionSlide#motivation
  %section.middle
    %h2 Motivation

.slide
  %header
    %h1 Motivation
  %section
    .left
      %h3 Current application
      =image_tag("/presentation_code/images/if_scattered.svg",:width=>"200px")
    .big-arrow.left
      %br
      ⇨
    .right
      %h3 Intended application
      =image_tag("/presentation_code/images/if_centralized.svg",:width=>"400px")
    .clear
    %ul.bullets
      %li No language-level support for this kind of adaptations
      %li New paradigms emerged to address the adaptable application concern
      %li Solutions exist, but improvements are needed to be industrialy ready


// ======== Objectives ========
.slide.transitionSlide#objectives
  %section.middle
    %h2 Objectives
    %p

.slide
  %header
    %h1 Objectives
  %section.middle
    %p
      %ul.bullets
        %li Solve the problem by merging COP and FOP paradigms
        %li Use Ruby, a real-world language
        %li Integrate the solution in Ruby on Rails applications
        %li Provide an industrialy ready and validated solution

// ======== Approach ========
.slide.transitionSlide#approach
  %section.middle
    %h2 Approach
    %p

.slide
  %header
    %h1 Approach
    %h2 Context as a Feature
  %section.middle
    %h2 Concepts of COP & FOP are complementary
    %p
      a
      %strong context
      reifies a situation relevant for the application behaviour
      %br
      a
      %strong feature
      reifies a functionality visible to stakeholders

    .big-arrow
      ⇩
    %p
      %strong Context as a Feature
      merges the COP & FOP paradigms by expressing a
      %strong feature
      as being a
      %strong context
      with extra capabilities

.slide.subTransitionSlide
  %section.middle
    %h2 Approach
    %p The Phenomenal Gem

.slide
  %header
    %h1 Approach
    %h2 Phenomenal
  %section
    %p
      The Phenomenal Gem is a pure Ruby COP framework which provides:
    %ul.bullets
      %li Contexts
      %li Features through Context as a Feature
      %li Behavioral adaptations
      %li Relationships
      %li Visualization tool
      %li Lightweight domain specific language

.slide
  %header
    %h1 Approach
    %h2 Phenomenal: Define contexts and features
  %section
    .code_snippet.left
      %h3 Code
      =pygments("public/presentation_code/define_context.rb")
    .code_graphical_view
      %h3 Context Visualization
      =image_tag("/presentation_code/graphical_views/define_context.rb.png")
    .clear
    %ul.bullets
      %li <span class="highlight">context <span class="ss">:Evening</span></span> defines a new context with name "Evening"
      %li <span class="highlight">feature <span class="ss">:DayTimesSense</span></span> defines a new feature with name "DayTimesSense"

.slide
  %header
    %h1 Approach
    %h2 Phenomenal: Define adaptations
  %section
    .code_snippet
      %h3 Code
      =pygments("public/presentation_code/define_adaptation.rb")
      %ul.bullets
        %li <span class="highlight">adaptation_for <span class="s2">PagesHelper</span></span> specifies the class to be adapted
        %li <span class="highlight">adapt <span class="ss">:phenomenal_color</span></span> adapts the instance method
        %li <span class="highlight">proceed</span> calls "super context" implementation

.slide
  %header
    %h1 Approach
    %h2 Phenomenal: Define combined contexts
  %section
    .code_snippet.left{:style=>"width:250px;"}
      %h3 Code
      =pygments("public/presentation_code/define_combined_context.rb")
    .code_graphical_view
      %h3 Context Visualization
      =image_tag("/presentation_code/graphical_views/define_combined_context.rb.png",:width=>"560px")
    .clear
    %ul.bullets
      %li Defines the combined context <span class="highlight"><span class="ss">"DayTimesSense,Evening"</span></span>
      %li Allows to specify behaviour specific for a combination of contexts

.slide
  %header
    %h1 Approach
    %h2 Phenomenal: Define relationships
  %section
    .code_snippet.left{:style=>"width:510px;margin-right:0px"}
      %h3 Code
      =pygments("public/presentation_code/define_relationship.rb")
    .code_graphical_view
      %h3 Context Visualization
      =image_tag("/presentation_code/images/defineRelationship.svg",:width=>"315px")
    .clear
    %ul.bullets
      %li <span class="highlight">implications_for <span class="ss">:InternetExplorer, :on</span>=><span class="ss">:Windows</span></span>
      %li <span class="highlight">implies <span class="ss">:Windows</span></span>
      %li Other relationships are available

.slide.subTransitionSlide
  %section.middle
    %h2 Approach
    %p The Phenomenal Rails Gem

.slide
  %header
    %h1 Approach
    %h2 Phenomenal Rails
  %section
    %p
      The Phenomenal Rails Gem integrates the Phenomenal Gem into Ruby on Rails
    %ul.bullets
      %li File structure integration
      %li Context activation condition
      %li View adaptation

.slide
  %header
    %h1 Approach
    %h2 Phenomenal Rails: File Structure Integration
  %section
    .left
      %h3 From this
      =image_tag("/presentation_code/images/monolithicFiles.svg")
    .big-arrow.left
      %br
      ⇨
    .right
      %h3 To this
      =image_tag("/presentation_code/images/phenomenalFilesLight.svg")
    .clear
    %ul.bullets
      %li Standard RoR applications use a single MVC
      %li Phenomenal Rails Gem allows to use a MVC per context
      %li Each context folder contains the context definition and its MVC

.slide
  %header
    %h1 Approach
    %h2 Phenomenal Rails: Activation Condition
  %section
    .left.code_snippet{:style=>"margin-bottom:0px;"}
      =pygments("public/presentation_code/activation_condition.rb")
    .right
      =image_tag("/presentation_code/images/application_stack.svg",:width=>"350x")
    .clear
    %ul.bullets{:style=>"margin-top:0px;"}
      %li Contexts have to be activated per request
      %li
        <span class="highlight">activation_condition</span>
        allows to store a block evaluated before each request
      %li The block specifies which contexts have to be activated
      %li The block is evaluated only when the feature is active

.slide
  %header
    %h1 Approach
    %h2 Phenomenal Rails: View Adaptation
  %section
    %h2.center Views are not Ruby methods

    %h3 How to adapt this
    =pygments("public/presentation_code/announce.html.haml",:haml)
    %h3 Into this
    =pygments("public/presentation_code/adapted_announce.html.haml",:haml)

.slide
  %header
    %h1 Approach
    %h2 Phenomenal Rails: View Adaptation
  %section
    .left
      %h3 Base view
      =image_tag("/presentation_code/images/viewNotAdapted.svg")
    .right
      %h3 Adapted view
      =image_tag("/presentation_code/images/viewAdapted.svg")
    .clear
    %ul.bullets
      %li To adapt a view a context must define a file with the same name and views folder
      %li The file displayed is the one in active contexts with higher precedence

// ======== Validation ========
.slide.transitionSlide#validation
  %section.middle
    %h2 Validation
    %p

.slide
  %header
    %h1 Validation
    %h2 Benubo
  %section.center
    %p
      =image_tag("/presentation_code/images/benubo.png")
      %br
      SaaS ERP to manage SME activities developed by Belighted
    %p
      =image_tag("/presentation_code/images/benubo-features-on.png")
      %ul.bullets
        %li Validates our concepts
        %li Leads to improvements of our solution
        %li Provides industrial feedback
.slide
  %header
    %h1 Validation
    %h2 Feature as a Service
  %section.middle
    %p
      The development of the previous concepts and their application in Benubo lead to the notion of
      %strong Feature as a Service
    %ul.bullets
      %li FaaS pushes the idea of Software as a Service further
      %li Allows to sell sub-components of an application to users
      %li Doable very easily with the Phenomenal Rails Gem
    %p=link_to "www.phenomenal-gem.com", :root

.slide
  %header
    %h1 Validation
    %h2 Benchmarks
  %section
    %p.center
      =image_tag("/presentation_code/images/benchmark.svg",:width=>"600px")
    %ul.bullets
      %li
        %strong.green Refactoring:
        Original application refactored in persistent features
      %li
        %strong.blue FaaS:
        Enabling Feature as a Service on the refactored application

// ======== Contributions ========
.slide.transitionSlide#contributions
  %section.middle
    %h2 Contributions
    %p

.slide
  %header
    %h1 Contributions
  %section
    %h2 Concepts
    %ul.bullets
      %li Context as a Feature
      %li Feature as a Service

    %h2 Implementation
    %ul.bullets
      %li Phenomenal & Phenomenal Rails Gems
      %li Visualization tool
      %li Activation condition
      %li Validation case-study (Benubo)
      %li Lightweight domain specific language

// ======== Conclusion ========
.slide.transitionSlide#conclusion
  %section.middle
    %h2 Conclusion
    %p

.slide
  %header
    %h1 Conclusion
  %section.middle
    %ul.bullets
      %li First step towards merging COP & FOP paradigms
      %li
        <span class="highlight"><span class="nb">require</span> <span class="s2">&quot;phenomenal&quot;</span></span>
        allows to adapt any existing Ruby application easily
      %li Enhanced dynamic adaptability at a reasonable cost
      %li Validated on a real Software as a Service

.slide
  %header
    %h1 That's the real story

  %section.middle.formula{"data-build"=>"data-build"}
    %span= image_tag("ruby.png",:height=>"104px")
    +
    %span= image_tag("rails.png",:height=>"104px")
    +
    %span= image_tag("pheno_logo.png",:height=>"104px")
    \=
    %span.hearth ♥

    %span
      =link_to "www.phenomenal-gem.com", :root

// ======== Questions ? ========
.slide
  %section#question-slide.middle
    %h2 Questions ?

app/views/shared/_context.html.haml
%tr
  %td
    = context.to_s
  %td
    = context.class
  %td
    -if context.active?
      =image_tag "icons/active_context.png"
    -else 
      =image_tag "icons/inactive_context.png"
  %td
    = context.activation_count
  %td
    -context.adaptations.each do |a|
      =render "shared/context_adaptation", :adaptation=>a
      %br

app/views/shared/_context_adaptation.html.haml
%strong=adaptation.klass
\:
=adaptation.method_name

app/views/shared/_deactivated_module.html.haml
Sorry, this module is deactivated :(

app/views/shared/_keep_calm.html.haml
.keep_calm
  =image_tag "others/Master-Shifu-128.png"
  %br
  %strong Keep calm! We are working hard on it...